stryker4s {
  mutate = [
    "src/main/scala/**/*.scala"
  ]
  base-dir = "."
  report-dir = "target/stryker4s-report"
  reporters = ["html"]
  scala-dialect = "scala3"
  timeout-factor = 1.5
  legacy-test-runner = true
}
